global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "jenkins"
    metrics_path: /prometheus/
    static_configs:
      - targets: ["192.168.50.5:8080"]

  - job_name: "tp-foyer-app"
    metrics_path: "/actuator/prometheus/"
    static_configs:
      - targets: ["app-tp-foyer:8089"]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.50.5:9100']
